### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by joao-neves95** [joao-neves95/ClassStudio#33]
- [x] Ability to remove selected files/directories to compile (without having to change to the About tab).
- [x] Better convertion menu mapping.

**Comment by jo-neves** [comment]
https://github.com/joao-neves95/ClassStudio/commit/2a24d09fd7695b7f824dc968f45e44f3644d9d67
https://github.com/joao-neves95/ClassStudio/commit/d8d843817a617b0a5d6ad1cb56fc4b95d0964e5d
